INSERT INTO Stations (name, location) VALUES
('Cairo', 'Cairo'),
('Giza', 'Giza'),
('Alexandria', 'Alexandria'),
('Aswan', 'Aswan'),
('Luxor', 'Luxor'),
('Sohag', 'Sohag'),
('Minya', 'Minya'),
('Qena', 'Qena'),
('Zagazig', 'Sharqia'),
('Tanta', 'Gharbia'),
('Mansoura', 'Dakahlia'),
('Port Said', 'Port Said'),
('Ismailia', 'Ismailia'),
('Suez', 'Suez'),
('Beni Suef', 'Beni Suef'),
('Damietta', 'Damietta'),
('Faiyum', 'Faiyum'),
('Asyut', 'Asyut'),
('Banha', 'Qalyubia'),
('Shibin El Kom', 'Monufia'),
('Damanhour', 'Beheira'),
('Banha', 'Qalyubia');
GO